### ISSUE TITLE
AssertStringEqual replaces \S and \s

### ISSUE THREAD

**Issue by rjrudman** [ethanli83/EFSqlTranslator#1]
AssertStringEqual is accidentally stripping all characters from both strings, so the equality check will always pass

**Comment by ethanli83** [comment]
hahaha, does it mean they were always pass? Thank you very much for the fix!

**Comment by rjrudman** [comment]
Hah yeah - A few a broken now (looks like minor things)- didn't get around to fixing them yesterday

**Comment by ethanli83** [comment]
That's fine, I  have fixed them. Thanks.
