### ISSUE TITLE
Support PostgresQL

### ISSUE THREAD

**Issue by ethanli83** [ethanli83/EFSqlTranslator#24]

**Comment by JasonYanPKI** [comment]
my query is simple:
    var groupedLineItems = lineItemQuery
                    .GroupBy(li => li.StateText)
                    .Select(g => new { Status = g.Key, 
                        LineCount = g.Count()
                    }); 
But it's still returning all lines and not counting on server side. Is it because I am using PostgreSQL?
And how to use your library, simply installing the nuget package? without any other code to initialize it with EntityFrameworkCore?

**Comment by ethanli83** [comment]
Did you just use EF for this query? EF does not do aggregation on SQL server, but loads all the data and process in memory. This is the point why I am making this library. My library translate the query into SQL and use Dapper to load data rather than using EF.

You can check out this repo:
https://github.com/ethanli83/EFSqlTranslatorExamples

I made it over the weekend to show how to use the package.

Basically, you just need to setup EF as you normally do, and install the package. Here is how you run queries using the library.

```
using (var db = new BloggingContext())
{
    var query = db.Blogs
        .GroupBy(b => b.Title)
        .Select(g => new { 
            Title = g.Key,
            Count = g.Count()
        });

     var blogs = db.Query(
        query,
        new EFModelInfoProvider(db),
        new SqliteObjectFactory(),
        out sql);
}
```
It does not officially support PostgresQL yet. I am working on it at the moment. You can still try it, and let me know if you have any issue.

Thanks,

**Comment by ethanli83** [comment]
Add support for PostgresQl ways of handling case sensitive.
Add support for PostgresQl string concatation.
