### ISSUE TITLE
Error on group when selecting new Entity

### ISSUE THREAD

**Issue by borisdj** [ethanli83/EFSqlTranslator#27]
Getting

> Object Reference not set to an instance of an object.

for this code:
````
var groupedItem = from p in context.Items.AsQueryable()
                   group p by p.CategoryId into GP
                   select new SumClass { CategoryId = GP.Key, Sum = GP.Sum(a => a.Value) };

var query = context.Query(groupedItem, new EFModelInfoProvider(context), new SqlObjectFactory());
var list = query.ToList();
````

Our chat regarding this on previous  [issue](https://github.com/ethanli83/EFSqlTranslator/issues/26) came to assumption that the _GUID_ used for PKs was the cause.
However that assumption was wrong. I have tested it with _int_ as PK, having no _GUIDs_ at all and still getting the same error, so it is something specific about conversion to custom class type(_SumClass_) on `select`.

It works when selecting to anonymous type like this
`select new SumClass { CategoryId = GP.Key, Sum = GP.Sum(a => a.Value) };`

Here is the sample with `select new SumClass` error:
[link](https://www.dropbox.com/s/aansv8zqyd27zb7/EFSqlTranslatorSample.zip?dl=0)

**Comment by ethanli83** [comment]
Hi, @borisdj,

I had a look at it, and I just realised that I have not implement NewExpression yet, so filling a class is not supported at the moment. 

I will be working on it.

Thanks

**Comment by ethanli83** [comment]
Hi @borisdj,

I just made a hotfix in Translation.1.2.6-rc1. Let me know if you are still having issue with the query.

You made still need the TypeHandler if guid.

Thanks

**Comment by borisdj** [comment]
Now it works.
Interestingly it even works with _Guid_, without need for _TypeHandler_ at all.
So I guest you can close this issue completely as well.

**Comment by ethanli83** [comment]
Oh, cool, maybe Dapper has fixed it at some stage. kkk.

Thanks

**Comment by borisdj** [comment]
All good.
Thx
