### ISSUE TITLE
question

### ISSUE THREAD

**Issue by pentest30** [ethanli83/EFSqlTranslator#29]
is there any example about using EfSqlTranslator with dapper ?

**Comment by pentest30** [comment]
so my dbcontext should inherit from dbContext of EF ?

**Comment by ethanli83** [comment]
Yes, your dbcontext be a subclass of DbContext from EF.

**Comment by ethanli83** [comment]
Hi @pentest30, I am closing this question for now. If you have other questions, feel free to ask.

Thanks
