### ISSUE TITLE
Generating xyz != null rather than xyz IS NOT NULL

### ISSUE THREAD

**Issue by rjrudman** [ethanli83/EFSqlTranslator#3]
The test Test_Translate_Join_Select_Columns is now failing (after merging #1). The actual SQL is producing:

<pre>select sq0.*
from (
    select p0.'PostId' as 'PId', sq0.'Name' as 'Name'
    from Posts p0
    inner join Users u0 on p0.'UserId' = u0.'UserId'
    left outer join (
        select b0.'Name', b0.'BlogId' as 'BlogId_jk1'
        from Blogs b0
        left outer join (
            select p0.'BlogId' as 'BlogId_jk0'
            from Posts p0
            inner join Users u0 on p0.'UserId' = u0.'UserId'
            where u0.'UserName' is not null
            group by p0.'BlogId'
        ) sq0 on b0.'BlogId' = sq0.'BlogId_jk0'
        where sq0.'BlogId_jk0' != null
    ) sq0 on p0.'BlogId' = sq0.'BlogId_jk1' and u0.'UserName' = 'ethan'
) sq0</pre>

`where sq0.'BlogId_jk0' != null`

Should be `where sq0.'BlogId_jk0' IS NOT null`.

**Comment by ethanli83** [comment]
Cool, thanks. Totally miss this one.
