### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by JoshuaWebb** [ethanli83/EFSqlTranslator#32]
You've got a pretty serious SQL injection problem

Running the following query on http://linqrunner.daydreamer.io/

```csharp
db.Customers.Where(c => c.ContactTitle.StartsWith("b' or 1 = 1 -- "))
```

Returns all of the Customer rows, but should actually return none.

![image](https://user-images.githubusercontent.com/6722399/27666560-e99849d2-5cb7-11e7-9428-4cddaa37ab29.png)

**Comment by ethanli83** [comment]
Hi @JoshuaWebb,

I have fixed the problem by escaping single quote in string.
I will update the runner when I get a chance.

Thanks
