### ISSUE TITLE
Contains()/Any() not supported for lists?

### ISSUE THREAD

**Issue by Shaddix** [ethanli83/EFSqlTranslator#43]
Is something like the following supported?
```
var ids = new[] {1, 2, 3};
_context.Table.Where(x=>ids.Contains(x.Id));
//or
_context.Table.Where(x=>ids.Any(z=> z== x.Id));
```

Can you think of any workaround for the queries like that?.. (SELECT * FROM Table WHERE Id In (1, 2, 3))
Thanks!

**Comment by ethanli83** [comment]
hi @Shaddix,

I add a method 'In' to support this use case, here is the syntax:
```
var ids = new[] {2, 3, 5};
var query = db.Blogs.Where(b => b.BlogId.In(1, 2, 4) && b.BlogId.In(ids));
```
and it will be translated into:
```
select b0.*
from Blogs b0
where (b0.BlogId in (1, 2, 4)) and (b0.BlogId in (2, 3, 5))
```

Hope this will solve your issue.

Also, the translator supports plugin translator. So if you have some idea or some custom translation to perform, maybe you can try it out. 

There is an example in TranslationPluginTests.cs

As usual, let me if you have issue,

Thanks

**Comment by Shaddix** [comment]
Thanks a lot, especially for pointing to the `TranslationPluginTests` example, it will definitely help!
