### ISSUE TITLE
Full Entities can't be used as a result of Select

### ISSUE THREAD

**Issue by Shaddix** [ethanli83/EFSqlTranslator#44]
Simple case 
```
db.Blogs.Select( x => new
                    {
                        blog = x,
                    }); 
```
Real life scenario:
```
var query = db.Blogs.Join(db.Posts, (blog, post) => blog.BlogId == post.BlogId, (blog, post) => new
                    {
                        blog,
                        blog.BlogId, 
                        post.PostId,
                        post
                    });
```

Returns
```
Result:
[
  {
    "blog": null,
    "BlogId": 1,
    "PostId": 1,
    "post": null
  },
  {
    "blog": null,
    "BlogId": 1,
    "PostId": 2,
    "post": null
  }
]
```

**Comment by ethanli83** [comment]
Hi @Shaddix,

This is going to be difficult to support as the translator is using Dapper to fill the query result, and it does not support this use case.

To make this select method works, it requires custom fill function.

I will have a look at if it is possible to do so, but I can't guarantee anything, kk.

Thanks

**Comment by ethanli83** [comment]
Hi @Shaddix,

I have added basic support for this in version 1.2.12.

Now you can fill result like this:
```
var query = db.Blogs.Select(x => new
{
    UId = x.UserId,
    Blog = x,
    UName = x.User.UserName,
    BUser = x.User
});
```
Few things to be aware of:
  1, this will only support filling Entity not support Array or List, for example
```
var query = db.Blogs.Select(x => new
{
    List = x.Comments
});
```
  2, it does not support filling anonymous as property, for example 
```
var query = db.Blogs.Select(x => new
{
    Anonymous = new { x.BlogId }
});
```
  3, Include will not work on entity properties of anonymous, for example
```
var query = db.Blogs.Select(x => new
{
    Blog = x
}).Include(b => b.Blog.User); // this will not work
```
  4, As I need to reflection to fill objects, filling entity properties of anonymous will be slower than filling an entity normally (about 20% slower).

Let me know if that works for you.

Thanks

**Comment by Shaddix** [comment]
Thanks a lot! All constraints make sense, so I don't see any problem with it.

However, there's an issue with the following query:
```
var query = db.Blogs.Select(x => new
                    {
                        Blog = x,
                    });
```

It throws "Result column name 'Name' is not match property name 'Url'". I assume that's because properties within a class are not in alphabetical order (as returned from SQL query).

Fix is attached as pull request

**Comment by ethanli83** [comment]
@Shaddix,

You are right about the column is in alphabetical order. Also thanks for the pull request! 

I notice that the primary key column is an exception from the ordering, so I made a fix to this issue with a different approach, and add some unit tests.

The change has been made in version 1.2.14.

Let me know if that fixes the problem for you.

Thanks again!

**Comment by ethanli83** [comment]
Hi @Shaddix 

I will close this issue for now. You can reopen it if the fix has any issue. Also, I just  pushed two nuget packages (Translation-1.3.0-rc1 and EFModels-1.2.0-rc1) which support netstandard2.0. You can try them out if you want to.

Thanks
