### ISSUE TITLE
Details on usage

### ISSUE THREAD

**Issue by mehmetilker** [ethanli83/EFSqlTranslator#51]
It looks promising, thank you for your work. (Especially when we think how long we have been waiting for group by feature for EFCore) 

I did not have a chance to try but could you clarify how to use it with EFCore And/Or Dapper.

I need Poco classes anyway, but do I need EFCore context as well.
I need Dapper library I guess but how will I tell Dapper to utilize EFSqlTranslator ?

Btw this site is not working. http://linqrunner.daydreamer.io/
Maybe there are examples but can not see.

**Comment by ethanli83** [comment]
@mehmetilker , sorry for the late responsive. 

You can check out the EFSqlTranslator.ConsoleApp project for details on how to set things up. It is basically an example project.

You  do need the EFCore context as will as the translator will be using it to get information such as relationship. You do not need manually setup Dapper for the translator, this is an extension function which will send the translated SQL to Dapper.

I am working on finding a new home for linqrunner site, my AWS free tire just expired, kk.

**Comment by mehmetilker** [comment]
I will take a look, thanks for clarifications.
