### ISSUE TITLE
DistinctCount feature

### ISSUE THREAD

**Issue by alexeyfadeev** [ethanli83/EFSqlTranslator#53]
Now it's impossible to generate such query with any ORM:

SELECT [CustomerId], 
     COUNT(*) AS [DealCount],
     COUNT(DISTINCT CompanyId) AS [CompanyDealCount]
   FROM [Deal]
   GROUP BY [CustomerId]

The reason is there is no aggregate method "DistinctCount" (or smth like this) in LINQ.

I want to add such extension method into EFSqlTranslator (for IQueriable<> and IEnumerable<> both). Then we can create queries like this:

var query = context.Deals
       .GroupBy(x => x.CustomerId)
       .Select(g => new
       {
           CustomerId = g.Key,
           DealCount = g.Count(),
           CompanyDealCount = g.DistinctCount(x => x.CompanyId)           
       });

For IQueriable<> it will generate "COUNT(DISTINCT ...)" SQL.
For IEnumerable<> it will be translated into "g.Select(x => x.CompanyId).Distinct().Count()" (it can be useful for unit tests with mocks).

What are you thinking about?

**Comment by ethanli83** [comment]
Agree,

`DistinctCount` will be a very useful thing. I think we can put the translation for `IEnumerable` in a file like `AggregationExtensions`, and create a `DistinctCountTranslater` similar to the `CountTranslater`.

It is a great idea.

Thanks @alexeyfadeev

**Comment by ethanli83** [comment]
By the way, for the `IEnumerable` translation, I think you may just need to do `g.Distinct(x => x.CompanyId).Count()`

**Comment by alexeyfadeev** [comment]
Yes, sure

**Comment by ethanli83** [comment]
Cool, do you want me to implement it, or you would like to give a go?

**Comment by alexeyfadeev** [comment]
Let me try

**Comment by ethanli83** [comment]
@alexeyfadeev 

I just realise that Distinct was not supported, so I spent some time to implement it. You can take a look at this [commit](https://github.com/ethanli83/EFSqlTranslator/commit/49bfbc0a91b6a01a6f9b09e5f47d90345b45b8df), it may help you a bit on implementing `DistinctCount`.

**Comment by alexeyfadeev** [comment]
I believe it will help!

**Comment by ethanli83** [comment]
Completed.
