### ISSUE TITLE
Aggregation functions could generate ArgumentNullException

### ISSUE THREAD

**Issue by alexeyfadeev** [ethanli83/EFSqlTranslator#57]
It works fine:
`var query = db.Blogs.Select(b => new { b.Name, cnt = b.Posts.Sum(p => p.PostId) });`

But if we don't use an anonymous type:
`var query = db.Blogs.Select(b => b.Posts.Sum(p => p.PostId));`
then we can generate SQL string
`var script = QueryTranslator.Translate(query.Expression, new EFModelInfoProvider(db), new SqlObjectFactory());`
`var sql = script.ToString();`
but execution of this query raises an exception:
`var result = db.Query(query, new EFModelInfoProvider(db), new SqlObjectFactory()).ToList();`
`// ArgumentNullException`

**Comment by ethanli83** [comment]
@alexeyfadeev ,

This issue has been fixed. Please check out the new version (2.2.2). It also contains your fix for #56 .

Thanks

**Comment by alexeyfadeev** [comment]
@ethanli83 I checked, now it works fine

This problem happened on query executon, e.g
`db.Query(query, ...).ToList();`
Now it's fixed.

Just SQL generation 
`QueryTranslator.Translate(query.Expression, ...).ToString();`
worked before your fixed, and still works.

Maybe we need tests with query execution?

**Comment by ethanli83** [comment]
@alexeyfadeev ,

This is odd. When I was fixing the issue, it thrown exceptions in both cases.
And base on what I changed, it should not work for both scenarios.

But you raise a very good point, the execution does fall short on testing. 
I have created an issue #58 for adding unit tests on execution. 
I will be adding some unit tests around execution.

Thanks.
